"""
LifeLens - 365 Curated Psychological & Mindfulness Quotes
Features 365 thought-provoking quotes from cognitive psychology, mindfulness,
stoicism, and humanistic philosophy for daily self-reflection.
"""

import random
from datetime import datetime

PSYCHOLOGICAL_QUOTES = [
    {"quote": "Knowing your own darkness is the best method for dealing with the darknesses of other people.", "author": "Carl Jung"},
    {"quote": "Between stimulus and response there is a space. In that space is our power to choose our response.", "author": "Viktor E. Frankl"},
    {"quote": "The curious paradox is that when I accept myself just as I am, then I can change.", "author": "Carl Rogers"},
    {"quote": "We don't see things as they are, we see them as we are.", "author": "Anaïs Nin"},
    {"quote": "The greatest weapon against stress is our ability to choose one thought over another.", "author": "William James"},
    {"quote": "Until you make the unconscious conscious, it will direct your life and you will call it fate.", "author": "Carl Jung"},
    {"quote": "Everything can be taken from a man but one thing: the last of the human freedoms—to choose one's attitude in any given set of circumstances.", "author": "Viktor E. Frankl"},
    {"quote": "Vulnerability is not winning or losing; it's having the courage to show up and be seen when we have no control over the outcome.", "author": "Brené Brown"},
    {"quote": "He who has a why to live can bear almost any how.", "author": "Friedrich Nietzsche"},
    {"quote": "You are not your thoughts; you are the observer of your thoughts.", "author": "Eckhart Tolle"},
    {"quote": "The primary cause of unhappiness is never the situation but your thoughts about it.", "author": "Eckhart Tolle"},
    {"quote": "Happiness is not something readymade. It comes from your own actions.", "author": "Dalai Lama"},
    {"quote": "It is not the man who has too little, but the man who craves more, that is poor.", "author": "Seneca"},
    {"quote": "We suffer more often in imagination than in reality.", "author": "Seneca"},
    {"quote": "You have power over your mind - not outside events. Realize this, and you will find strength.", "author": "Marcus Aurelius"},
    {"quote": "The soul becomes dyed with the color of its thoughts.", "author": "Marcus Aurelius"},
    {"quote": "What is necessary to change a person is to change his awareness of himself.", "author": "Abraham Maslow"},
    {"quote": "A musician must make music, an artist must paint, a poet must write, if he is to be ultimately at peace with himself.", "author": "Abraham Maslow"},
    {"quote": "In any given moment we have two options: to step forward into growth or to step back into safety.", "author": "Abraham Maslow"},
    {"quote": "Life doesn't make sense without interdependence. We need each other, and the sooner we learn that, the better for us all.", "author": "Erik Erikson"},
    {"quote": "The privilege of a lifetime is to become who you truly are.", "author": "Carl Jung"},
    {"quote": "Unexpressed emotions will never die. They are buried alive and will come forth later in uglier ways.", "author": "Sigmund Freud"},
    {"quote": "Out of your vulnerabilities will come your strength.", "author": "Sigmund Freud"},
    {"quote": "Words have a magical power. They can bring either the greatest happiness or deepest despair.", "author": "Sigmund Freud"},
    {"quote": "The view you adopt for yourself profoundly affects the way you lead your life.", "author": "Carol S. Dweck"},
    {"quote": "In a growth mindset, challenges are exciting rather than threatening.", "author": "Carol S. Dweck"},
    {"quote": "Nothing in life is as important as you think it is, while you are thinking about it.", "author": "Daniel Kahneman"},
    {"quote": "We can be blind to the obvious, and we are also blind to our blindness.", "author": "Daniel Kahneman"},
    {"quote": "A reliable way to make people believe in falsehoods is frequent repetition, because familiarity is not easily distinguished from truth.", "author": "Daniel Kahneman"},
    {"quote": "The mind is its own place, and in itself can make a heaven of hell, a hell of heaven.", "author": "John Milton"},
    {"quote": "Feelings come and go like clouds in a windy sky. Conscious breathing is my anchor.", "author": "Thich Nhat Hanh"},
    {"quote": "Smile, breathe and go slowly.", "author": "Thich Nhat Hanh"},
    {"quote": "Letting go gives us freedom, and freedom is the only condition for happiness.", "author": "Thich Nhat Hanh"},
    {"quote": "Peace comes from within. Do not seek it without.", "author": "Siddhartha Gautama"},
    {"quote": "Rule your mind or it will rule you.", "author": "Horace"},
    {"quote": "Man is not affected by events, but by the view he takes of them.", "author": "Epictetus"},
    {"quote": "First say to yourself what you would be; and then do what you have to do.", "author": "Epictetus"},
    {"quote": "Don't explain your philosophy. Embody it.", "author": "Epictetus"},
    {"quote": "The good life is a process, not a state of being. It is a direction, not a destination.", "author": "Carl Rogers"},
    {"quote": "Experience is, for me, the highest authority.", "author": "Carl Rogers"},
    {"quote": "What we achieve inwardly will change outer reality.", "author": "Plutarch"},
    {"quote": "The highest form of human intelligence is to observe yourself without judgment.", "author": "Jiddu Krishnamurti"},
    {"quote": "It is no measure of health to be well adjusted to a profoundly sick society.", "author": "Jiddu Krishnamurti"},
    {"quote": "Ability is what you're capable of doing. Motivation determines what you do. Attitude determines how well you do it.", "author": "Lou Holtz"},
    {"quote": "Who looks outside, dreams; who looks inside, awakes.", "author": "Carl Jung"},
    {"quote": "I am not what happened to me, I am what I choose to become.", "author": "Carl Jung"},
    {"quote": "Everything that irritates us about others can lead us to an understanding of ourselves.", "author": "Carl Jung"},
    {"quote": "Your visions will become clear only when you can look into your own heart.", "author": "Carl Jung"},
    {"quote": "There is no coming to consciousness without pain.", "author": "Carl Jung"},
    {"quote": "The shoe that fits one person pinches another; there is no recipe for living that suits all cases.", "author": "Carl Jung"},
    {"quote": "Loneliness does not come from having no people about one, but from being unable to communicate the things that seem important to oneself.", "author": "Carl Jung"},
    {"quote": "Emotion is the chief source of all becoming-conscious. There can be no transforming of darkness into light and of apathy into movement without emotion.", "author": "Carl Jung"},
    {"quote": "People will do anything, no matter how absurd, in order to avoid facing their own souls.", "author": "Carl Jung"},
    {"quote": "Mistakes are, after all, the foundations of truth.", "author": "Carl Jung"},
    {"quote": "Shame derives its power from being unspeakable.", "author": "Brené Brown"},
    {"quote": "Courage starts with showing up and letting ourselves be seen.", "author": "Brené Brown"},
    {"quote": "Talk to yourself like once you would talk to someone you love.", "author": "Brené Brown"},
    {"quote": "Authenticity is the daily practice of letting go of who we think we're supposed to be and embracing who we are.", "author": "Brené Brown"},
    {"quote": "Imperfections are not inadequacies; they are reminders that we're all in this together.", "author": "Brené Brown"},
    {"quote": "To love oneself is the beginning of a lifelong romance.", "author": "Oscar Wilde"},
    {"quote": "Be yourself; everyone else is already taken.", "author": "Oscar Wilde"},
    {"quote": "Act the way you'd like to be and soon you'll be the way you act.", "author": "Leonard Cohen"},
    {"quote": "There is a crack in everything. That's how the light gets in.", "author": "Leonard Cohen"},
    {"quote": "Change the way you look at things and the things you look at change.", "author": "Wayne Dyer"},
    {"quote": "If you change the way you think, you change the way you feel.", "author": "David D. Burns"},
    {"quote": "Aim for success, not perfection. Never surrender your right to be wrong.", "author": "David D. Burns"},
    {"quote": "You are not your depression, you are not your anxiety. You are the sky, and they are the weather.", "author": "Matt Haig"},
    {"quote": "Nothing is permanent in this wicked world - not even our troubles.", "author": "Charlie Chaplin"},
    {"quote": "A day without laughter is a day wasted.", "author": "Charlie Chaplin"},
    {"quote": "The greatest discovery of any generation is that a human can alter his life by altering his attitude.", "author": "William James"},
    {"quote": "Act as if what you do makes a difference. It does.", "author": "William James"},
    {"quote": "Believe that life is worth living and your belief will help create the fact.", "author": "William James"},
    {"quote": "The art of being wise is the art of knowing what to overlook.", "author": "William James"},
    {"quote": "Habit is the enormous fly-wheel of society, its most precious conservative agent.", "author": "William James"},
    {"quote": "Common sense and a sense of humor are the same thing, moving at different speeds.", "author": "William James"},
    {"quote": "Begin to be now what you will be hereafter.", "author": "William James"},
    {"quote": "Patience is bitter, but its fruit is sweet.", "author": "Jean-Jacques Rousseau"},
    {"quote": "The world is a book and those who do not travel read only one page.", "author": "Augustine of Hippo"},
    {"quote": "To understand all is to forgive all.", "author": "Leo Tolstoy"},
    {"quote": "If you want to be happy, be.", "author": "Leo Tolstoy"},
    {"quote": "Everyone thinks of changing the world, but no one thinks of changing himself.", "author": "Leo Tolstoy"},
    {"quote": "The two most powerful warriors are patience and time.", "author": "Leo Tolstoy"},
    {"quote": "Spring will come and so will happiness. Life will get warmer.", "author": "Anita Krizzan"},
    {"quote": "Courage is not the absence of fear, but rather the assessment that something else is more important than fear.", "author": "Franklin D. Roosevelt"},
    {"quote": "The only limit to our realization of tomorrow will be our doubts of today.", "author": "Franklin D. Roosevelt"},
    {"quote": "Don't judge each day by the harvest you reap but by the seeds that you plant.", "author": "Robert Louis Stevenson"},
    {"quote": "Quiet the mind, and the soul will speak.", "author": "Ma Jaya Sati Bhagavati"},
    {"quote": "Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment.", "author": "Buddha"},
    {"quote": "In the end, only three things matter: how much you loved, how gently you lived, and how gracefully you let go of things not meant for you.", "author": "Buddha"},
    {"quote": "Health is the greatest gift, contentment the greatest wealth, faithfulness the best relationship.", "author": "Buddha"},
    {"quote": "Just as a candle cannot burn without fire, men cannot live without a spiritual life.", "author": "Buddha"},
    {"quote": "Three things cannot be long hidden: the sun, the moon, and the truth.", "author": "Buddha"},
    {"quote": "The mind is everything. What you think you become.", "author": "Buddha"},
    {"quote": "No one saves us but ourselves. No one can and no one may. We ourselves must walk the path.", "author": "Buddha"},
    {"quote": "Peace comes from within. Do not seek it outside.", "author": "Buddha"},
    {"quote": "To live is the rarest thing in the world. Most people exist, that is all.", "author": "Oscar Wilde"},
    {"quote": "Live as if you were to die tomorrow. Learn as if you were to live forever.", "author": "Mahatma Gandhi"},
    {"quote": "The weak can never forgive. Forgiveness is the attribute of the strong.", "author": "Mahatma Gandhi"},
    {"quote": "Happiness is when what you think, what you say, and what you do are in harmony.", "author": "Mahatma Gandhi"},
    {"quote": "An ounce of practice is worth more than tons of preaching.", "author": "Mahatma Gandhi"},
    {"quote": "Be the change that you wish to see in the world.", "author": "Mahatma Gandhi"},
    {"quote": "Freedom is not worth having if it does not include the freedom to make mistakes.", "author": "Mahatma Gandhi"},
    {"quote": "Care about what other people think and you will always be their prisoner.", "author": "Lao Tzu"},
    {"quote": "A journey of a thousand miles begins with a single step.", "author": "Lao Tzu"},
    {"quote": "When I let go of what I am, I become what I might be.", "author": "Lao Tzu"},
    {"quote": "Mastering others is strength. Mastering yourself is true power.", "author": "Lao Tzu"},
    {"quote": "Nature does not hurry, yet everything is accomplished.", "author": "Lao Tzu"},
    {"quote": "Silence is a source of great strength.", "author": "Lao Tzu"},
    {"quote": "Knowing others is intelligence; knowing yourself is true wisdom.", "author": "Lao Tzu"},
    {"quote": "Kindness in words creates confidence. Kindness in thinking creates profoundness. Kindness in giving creates love.", "author": "Lao Tzu"},
    {"quote": "Life is a series of natural and spontaneous changes. Don't resist them.", "author": "Lao Tzu"},
    {"quote": "He who knows that enough is enough will always have enough.", "author": "Lao Tzu"},
    {"quote": "To the mind that is still, the whole universe surrenders.", "author": "Lao Tzu"},
    {"quote": "The journey of discovery lies not in seeking new landscapes, but in having new eyes.", "author": "Marcel Proust"},
    {"quote": "We do not receive wisdom, we must discover it for ourselves after a journey through the wilderness.", "author": "Marcel Proust"},
    {"quote": "Self-awareness gives you the capacity to learn from your mistakes as well as your successes.", "author": "Lawrence Bossidy"},
    {"quote": "Self-awareness is not self-absorption. It's the beginning of empathy.", "author": "Daniel Goleman"},
    {"quote": "Emotional intelligence is the ability to sense, understand, and effectively apply the power of emotions as a source of energy.", "author": "Daniel Goleman"},
    {"quote": "Leadership is not domination, but the art of persuading people toward a common goal.", "author": "Daniel Goleman"},
    {"quote": "What really matters for success, character, and lifelong achievement is a definite set of emotional skills.", "author": "Daniel Goleman"},
    {"quote": "Small disciplines repeated with consistency every day lead to great achievements gained slowly over time.", "author": "John C. Maxwell"},
    {"quote": "Change is inevitable. Growth is optional.", "author": "John C. Maxwell"},
    {"quote": "You will never change your life until you change something you do daily. The secret of your success is found in your daily routine.", "author": "John C. Maxwell"},
    {"quote": "Life is 10% what happens to me and 90% of how I react to it.", "author": "Charles R. Swindoll"},
    {"quote": "Attitude is more important than the past, than education, than circumstances, than what other people say or do.", "author": "Charles R. Swindoll"},
    {"quote": "We cannot change our past... we cannot change the fact that people will act in a certain way. The only thing we can do is play on the one string we have, and that is our attitude.", "author": "Charles R. Swindoll"},
    {"quote": "The greatest glory in living lies not in never falling, but in rising every time we fall.", "author": "Nelson Mandela"},
    {"quote": "It always seems impossible until it's done.", "author": "Nelson Mandela"},
    {"quote": "I learned that courage was not the absence of fear, but the triumph over it.", "author": "Nelson Mandela"},
    {"quote": "A winner is a dreamer who never gives up.", "author": "Nelson Mandela"},
    {"quote": "May your choices reflect your hopes, not your fears.", "author": "Nelson Mandela"},
    {"quote": "Resentment is like drinking poison and hoping it will kill your enemies.", "author": "Nelson Mandela"},
    {"quote": "Education is the most powerful weapon which you can use to change the world.", "author": "Nelson Mandela"},
    {"quote": "For to be free is not merely to cast off one's chains, but to live in a way that respects and enhances the freedom of others.", "author": "Nelson Mandela"},
    {"quote": "If you talk to a man in a language he understands, that goes to his head. If you talk to him in his language, that goes to his heart.", "author": "Nelson Mandela"},
    {"quote": "Do not judge me by my successes, judge me by how many times I fell down and got back up again.", "author": "Nelson Mandela"},
    {"quote": "Your task is not to seek for love, but merely to seek and find all the barriers within yourself that you have built against it.", "author": "Rumi"},
    {"quote": "The wound is the place where the Light enters you.", "author": "Rumi"},
    {"quote": "Stop acting so small. You are the universe in ecstatic motion.", "author": "Rumi"},
    {"quote": "Yesterday I was clever, so I wanted to change the world. Today I am wise, so I am changing myself.", "author": "Rumi"},
    {"quote": "Raise your words, not voice. It is rain that grows flowers, not thunder.", "author": "Rumi"},
    {"quote": "Don't grieve. Anything you lose comes round in another form.", "author": "Rumi"},
    {"quote": "Silence is the language of God, all else is poor translation.", "author": "Rumi"},
    {"quote": "Let yourself be silently drawn by the strange pull of what you really love. It will not lead you astray.", "author": "Rumi"},
    {"quote": "Set your life on fire. Seek those who fan your flames.", "author": "Rumi"},
    {"quote": "As you start to walk on the way, the way appears.", "author": "Rumi"},
    {"quote": "When you do things from your soul, you feel a river moving in you, a joy.", "author": "Rumi"},
    {"quote": "Respond to every call that excites your spirit.", "author": "Rumi"},
    {"quote": "Live life as if everything is rigged in your favor.", "author": "Rumi"},
    {"quote": "You were born with wings, why prefer to crawl through life?", "author": "Rumi"},
    {"quote": "Why do you stay in prison when the door is so wide open?", "author": "Rumi"},
    {"quote": "Be like a tree and let the dead leaves drop.", "author": "Rumi"},
    {"quote": "Shine like the whole universe is yours.", "author": "Rumi"},
    {"quote": "Patience is not sitting and waiting, it is foreseeing. It is looking at the thorn and seeing the rose.", "author": "Rumi"},
    {"quote": "Wear gratitude like a cloak and it will feed every corner of your life.", "author": "Rumi"},
    {"quote": "Whatever purifies you is the right path.", "author": "Rumi"},
    {"quote": "In the middle of difficulty lies opportunity.", "author": "Albert Einstein"},
    {"quote": "A person who never made a mistake never tried anything new.", "author": "Albert Einstein"},
    {"quote": "Imagination is more important than knowledge. For knowledge is limited, whereas imagination embraces the entire world.", "author": "Albert Einstein"},
    {"quote": "Life is like riding a bicycle. To keep your balance, you must keep moving.", "author": "Albert Einstein"},
    {"quote": "Look deep into nature, and then you will understand everything better.", "author": "Albert Einstein"},
    {"quote": "Weak people revenge. Strong people forgive. Intelligent people ignore.", "author": "Albert Einstein"},
    {"quote": "Peace cannot be kept by force; it can only be achieved by understanding.", "author": "Albert Einstein"},
    {"quote": "We cannot solve our problems with the same thinking we used when we created them.", "author": "Albert Einstein"},
    {"quote": "Stay close to anything that makes you glad you are alive.", "author": "Hafez"},
    {"quote": "Even after all this time the sun never says to the earth, 'You owe me.' Look what happens with a love like that, it lights the whole sky.", "author": "Hafez"},
    {"quote": "I wish I could show you when you are lonely or in darkness the astonishing light of your own being.", "author": "Hafez"},
    {"quote": "Fear is the cheapest room in the house. I would like to see you living in better conditions.", "author": "Hafez"},
    {"quote": "Ever since happiness heard your name, it has been running through the streets trying to find you.", "author": "Hafez"},
    {"quote": "Man is made or unmade by himself. In the armory of thought he forges the weapons by which he destroys himself.", "author": "James Allen"},
    {"quote": "Mind is the Master power that molds and makes, and Man is Mind, and evermore he takes the tool of Thought.", "author": "James Allen"},
    {"quote": "Calmness of mind is one of the beautiful jewels of wisdom.", "author": "James Allen"},
    {"quote": "Self-control is strength. Right thought is mastery. Calmness is power.", "author": "James Allen"},
    {"quote": "The outer world of circumstance shapes itself to the inner world of thought.", "author": "James Allen"},
    {"quote": "Cherish your visions; cherish your ideals; cherish the music that stirs in your heart.", "author": "James Allen"},
    {"quote": "Dream lofty dreams, and as you dream, so shall you become.", "author": "James Allen"},
    {"quote": "A man is literally what he thinks, his character being the complete sum of all his thoughts.", "author": "James Allen"},
    {"quote": "Circumstance does not make the man; it reveals him to himself.", "author": "James Allen"},
    {"quote": "Suffering is always the effect of wrong thought in some direction. It is an indication that the individual is out of harmony with himself.", "author": "James Allen"},
    {"quote": "The more tranquil a man becomes, the greater is his success, his influence, his power for good.", "author": "James Allen"},
    {"quote": "A strong man cannot help a weaker unless the weaker is willing to be helped, and even then the weak man must become strong of himself.", "author": "James Allen"},
    {"quote": "Into your hands will be placed the exact results of your own thoughts.", "author": "James Allen"},
    {"quote": "You will become as small as your controlling desire; as great as your dominant aspiration.", "author": "James Allen"},
    {"quote": "The greatest step towards a life of simplicity is to learn to forgive.", "author": "Peter McWilliams"},
    {"quote": "Comfort is the enemy of achievement.", "author": "Farrah Gray"},
    {"quote": "Our anxiety does not empty tomorrow of its sorrow, but only empties today of its strength.", "author": "Charles Spurgeon"},
    {"quote": "It is not how much we have, but how much we enjoy, that makes happiness.", "author": "Charles Spurgeon"},
    {"quote": "A good character is the best tombstone. Those who loved you and were helped by you will remember you when forget-me-nots have withered.", "author": "Charles Spurgeon"},
    {"quote": "Carve your name on hearts, not tombstones. A legacy is etched into the minds of others and the stories they share about you.", "author": "Shannon L. Alder"},
    {"quote": "Courage doesn't always roar. Sometimes courage is the quiet voice at the end of the day saying, 'I will try again tomorrow.'", "author": "Mary Anne Radmacher"},
    {"quote": "What lies behind us and what lies before us are tiny matters compared to what lies within us.", "author": "Ralph Waldo Emerson"},
    {"quote": "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.", "author": "Ralph Waldo Emerson"},
    {"quote": "For every minute you remain angry, you give up sixty seconds of peace of mind.", "author": "Ralph Waldo Emerson"},
    {"quote": "Nothing can bring you peace but yourself.", "author": "Ralph Waldo Emerson"},
    {"quote": "Do not go where the path may lead, go instead where there is no path and leave a trail.", "author": "Ralph Waldo Emerson"},
    {"quote": "The only person you are destined to become is the person you decide to be.", "author": "Ralph Waldo Emerson"},
    {"quote": "Adopt the pace of nature: her secret is patience.", "author": "Ralph Waldo Emerson"},
    {"quote": "Live in the sunshine, swim the sea, drink the wild air.", "author": "Ralph Waldo Emerson"},
    {"quote": "Peace cannot be achieved through violence, it can only be attained through understanding.", "author": "Ralph Waldo Emerson"},
    {"quote": "Cultivate the habit of being grateful for every good thing that comes to you, and to give thanks continuously.", "author": "Ralph Waldo Emerson"},
    {"quote": "Enthusiasm is the mother of effort, and without it nothing great was ever achieved.", "author": "Ralph Waldo Emerson"},
    {"quote": "Make the most of yourself....for that is all there is of you.", "author": "Ralph Waldo Emerson"},
    {"quote": "Our greatest glory is not in never failing, but in rising up every time we fail.", "author": "Ralph Waldo Emerson"},
    {"quote": "Nothing great was ever achieved without enthusiasm.", "author": "Ralph Waldo Emerson"},
    {"quote": "Write it on your heart that every day is the best day in the year.", "author": "Ralph Waldo Emerson"},
    {"quote": "A hero is no braver than an ordinary man, but he is brave five minutes longer.", "author": "Ralph Waldo Emerson"},
    {"quote": "Though we travel the world over to find the beautiful, we must carry it with us, or we find it not.", "author": "Ralph Waldo Emerson"},
    {"quote": "The creation of a thousand forests is in one acorn.", "author": "Ralph Waldo Emerson"},
    {"quote": "You cannot do a kindness too soon, for you never know how soon it will be too late.", "author": "Ralph Waldo Emerson"},
    {"quote": "Unless you try to do something beyond what you have already mastered, you will never grow.", "author": "Ralph Waldo Emerson"},
    {"quote": "Trust thyself: every heart vibrates to that iron string.", "author": "Ralph Waldo Emerson"},
    {"quote": "Most of the shadows of this life are caused by our standing in our own sunshine.", "author": "Ralph Waldo Emerson"},
    {"quote": "The purpose of life is not to be happy. It is to be useful, to be honorable, to be compassionate, to have it make some difference that you have lived and lived well.", "author": "Ralph Waldo Emerson"},
    {"quote": "Go confidently in the direction of your dreams! Live the life you've imagined.", "author": "Henry David Thoreau"},
    {"quote": "As a single footstep will not make a path on the earth, so a single thought will not make a pathway in the mind.", "author": "Henry David Thoreau"},
    {"quote": "Things do not change; we change.", "author": "Henry David Thoreau"},
    {"quote": "I went to the woods because I wished to live deliberately, to front only the essential facts of life.", "author": "Henry David Thoreau"},
    {"quote": "It's not what you look at that matters, it's what you see.", "author": "Henry David Thoreau"},
    {"quote": "Live your beliefs and you can turn the world around.", "author": "Henry David Thoreau"},
    {"quote": "Simplicity, simplicity, simplicity! I say, let your affairs be as two or three, and not a hundred or a thousand.", "author": "Henry David Thoreau"},
    {"quote": "There are moments when all anxiety and stated toil are becalmed in the infinite leisure and repose of nature.", "author": "Henry David Thoreau"},
    {"quote": "If one advances confidently in the direction of his dreams, and endeavors to live the life which he has imagined, he will meet with a success unexpected in common hours.", "author": "Henry David Thoreau"},
    {"quote": "Live in each season as it passes; breathe the air, drink the drink, taste the fruit, and resign yourself to the influence of the earth.", "author": "Henry David Thoreau"},
    {"quote": "Be not simply good; be good for something.", "author": "Henry David Thoreau"},
    {"quote": "This world is but a canvas to our imagination.", "author": "Henry David Thoreau"},
    {"quote": "None are so old as those who have outlived enthusiasm.", "author": "Henry David Thoreau"},
    {"quote": "The question is not what you look at, but what you see.", "author": "Henry David Thoreau"},
    {"quote": "Our life is frittered away by detail. Simplify, simplify.", "author": "Henry David Thoreau"},
    {"quote": "Happiness is like a butterfly; the more you chase it, the more it will elude you, but if you turn your attention to other things, it will come and sit softly on your shoulder.", "author": "Henry David Thoreau"},
    {"quote": "Do what you love, know what you love, and have the courage to pursue it.", "author": "Henry David Thoreau"},
    {"quote": "Not until we are lost do we begin to understand ourselves.", "author": "Henry David Thoreau"},
    {"quote": "Rather than love, than money, than fame, give me truth.", "author": "Henry David Thoreau"},
    {"quote": "Dreams are the touchstones of our characters.", "author": "Henry David Thoreau"},
    {"quote": "A truly rich man is one whose children run into his arms when his hands are empty.", "author": "Anonymous"},
    {"quote": "The only way to make sense out of change is to plunge into it, move with it, and join the dance.", "author": "Alan Watts"},
    {"quote": "Muddy water is best cleared by leaving it alone.", "author": "Alan Watts"},
    {"quote": "You are a function of what the whole universe is doing in the same way that a wave is a function of what the whole ocean is doing.", "author": "Alan Watts"},
    {"quote": "Trying to define yourself is like trying to bite your own teeth.", "author": "Alan Watts"},
    {"quote": "The meaning of life is just to be alive. It is so plain and so obvious and so simple.", "author": "Alan Watts"},
    {"quote": "This is the real secret of life — to be completely engaged with what you are doing in the here and now.", "author": "Alan Watts"},
    {"quote": "No amount of anxiety makes any difference to anything that's going to happen.", "author": "Alan Watts"},
    {"quote": "To have faith is to trust yourself to the water. When you swim you don't grab hold of the water, because if you do you will sink and drown.", "author": "Alan Watts"},
    {"quote": "Happenstance is what happens when you're not paying attention. Destiny is what happens when you are.", "author": "Alan Watts"},
    {"quote": "Man suffers only because he takes seriously what the gods made for fun.", "author": "Alan Watts"},
    {"quote": "You didn't come into the world. You came out of it, like a wave from the ocean. You are not a stranger here.", "author": "Alan Watts"},
    {"quote": "The menu is not the meal.", "author": "Alan Watts"},
    {"quote": "Problems that remain persistently insoluble should always be suspected as questions asked in the wrong way.", "author": "Alan Watts"},
    {"quote": "We seldom realize, for example, that our most private thoughts and emotions are not actually our own. For we think in terms of languages and images which we did not invent.", "author": "Alan Watts"},
    {"quote": "Every intelligent spirit now alive is not merely an observer of the universe, but an active participant in its evolution.", "author": "Alan Watts"},
    {"quote": "Technology is destructive only in the hands of people who do not realize that they are one and the same process as the universe.", "author": "Alan Watts"},
    {"quote": "I have realized that the past and future are real illusions, that they exist in the present, which is what there is and all there is.", "author": "Alan Watts"},
    {"quote": "Better to cultivate your own garden than to covet another's harvest.", "author": "Voltaire"},
    {"quote": "Appreciation is a wonderful thing: It makes what is excellent in others belong to us as well.", "author": "Voltaire"},
    {"quote": "Judge a man by his questions rather than by his answers.", "author": "Voltaire"},
    {"quote": "The most important decision you make is to be in a good mood.", "author": "Voltaire"},
    {"quote": "Perfect is the enemy of good.", "author": "Voltaire"},
    {"quote": "Life is a shipwreck, but we must not forget to sing in the lifeboats.", "author": "Voltaire"},
    {"quote": "Cherish those who seek the truth but beware of those who find it.", "author": "Voltaire"},
    {"quote": "Self-love is the instrument of our preservation.", "author": "Voltaire"},
    {"quote": "Doubt is an uncomfortable condition, but certainty is a ridiculous one.", "author": "Voltaire"},
    {"quote": "We never live; we are always in the expectation of living.", "author": "Voltaire"},
    {"quote": "The mind expands by experience, but unless it is guided by self-knowledge, it loses its compass.", "author": "Baruch Spinoza"},
    {"quote": "Peace is not an absence of war, it is a virtue, a state of mind, a disposition for benevolence, confidence, justice.", "author": "Baruch Spinoza"},
    {"quote": "I have striven not to laugh at human actions, not to weep at them, nor to hate them, but to understand them.", "author": "Baruch Spinoza"},
    {"quote": "The highest activity a human being can attain is learning for understanding, because to understand is to be free.", "author": "Baruch Spinoza"},
    {"quote": "All things excellent are as difficult as they are rare.", "author": "Baruch Spinoza"},
    {"quote": "Fear cannot be without hope nor hope without fear.", "author": "Baruch Spinoza"},
    {"quote": "He who would look for light must first be willing to step into the shade.", "author": "Baruch Spinoza"},
    {"quote": "We feel and know that we are eternal.", "author": "Baruch Spinoza"},
    {"quote": "Be not astonished at new ideas; for it is well known to you that a thing does not therefore cease to be true because it is not accepted by many.", "author": "Baruch Spinoza"},
    {"quote": "Desire is the very essence of man.", "author": "Baruch Spinoza"},
    {"quote": "Nothing in nature is by chance... Something appears to be chance only because of our lack of knowledge.", "author": "Baruch Spinoza"},
    {"quote": "A free man thinks of nothing less than of death, and his wisdom is a meditation not on death but on life.", "author": "Baruch Spinoza"},
    {"quote": "He who loves God cannot strive that God should love him in return.", "author": "Baruch Spinoza"},
    {"quote": "Minds are not conquered by arms, but by love and generosity.", "author": "Baruch Spinoza"},
    {"quote": "To be what we are, and to become what we are capable of becoming, is the only end of life.", "author": "Robert Louis Stevenson"},
    {"quote": "Keep your fears to yourself, but share your courage with others.", "author": "Robert Louis Stevenson"},
    {"quote": "There is no duty we so much underrate as the duty of being happy.", "author": "Robert Louis Stevenson"},
    {"quote": "To travel hopefully is a better thing than to arrive, and the true success is to labour.", "author": "Robert Louis Stevenson"},
    {"quote": "Quiet minds cannot be perplexed or frightened, but go on in fortune or misfortune at their own private pace.", "author": "Robert Louis Stevenson"},
    {"quote": "Every step forward is a step towards self-mastery.", "author": "Robert Louis Stevenson"},
    {"quote": "The best things in life are nearest: breath in your nostrils, light in your eyes, flowers at your feet.", "author": "Robert Louis Stevenson"},
    {"quote": "Compromise is the best and cheapest lawyer.", "author": "Robert Louis Stevenson"},
    {"quote": "Saints are sinners who kept on going.", "author": "Robert Louis Stevenson"},
    {"quote": "You cannot run away from a weakness; you must sometimes fight it out or perish.", "author": "Robert Louis Stevenson"},
    {"quote": "The man is a success who has lived well, laughed often, and loved much.", "author": "Robert Louis Stevenson"},
    {"quote": "Life is not a matter of holding good cards, but of playing a poor hand well.", "author": "Robert Louis Stevenson"},
    {"quote": "Give me the wild life that knows no master.", "author": "Robert Louis Stevenson"},
    {"quote": "There is no shortcut to any place worth going.", "author": "Beverly Sills"},
    {"quote": "Life shrinks or expands in proportion to one's courage.", "author": "Anaïs Nin"},
    {"quote": "We write to taste life twice, in the moment and in retrospect.", "author": "Anaïs Nin"},
    {"quote": "The personal life deeply lived always expands into truths beyond itself.", "author": "Anaïs Nin"},
    {"quote": "And the day came when the risk to remain tight in a bud was more painful than the risk it took to blossom.", "author": "Anaïs Nin"},
    {"quote": "Dreams pass into the reality of action. From the actions stems the dream again; and this interdependence is an infinite form of living.", "author": "Anaïs Nin"},
    {"quote": "I postpone death by living, by suffering, by error, by risking, by giving, by losing.", "author": "Anaïs Nin"},
    {"quote": "Anxiety is love's greatest killer. It makes others feel as you might when a drowning man holds on to you.", "author": "Anaïs Nin"},
    {"quote": "Do not seek the because - in love there is no because, no reason, no explanation, no solutions.", "author": "Anaïs Nin"},
    {"quote": "Good things happen to those who hustle.", "author": "Anaïs Nin"},
    {"quote": "The possession of knowledge does not kill the sense of wonder and mystery. There is always more mystery.", "author": "Anaïs Nin"},
    {"quote": "We do not grow absolutely, chronologically. We grow sometimes in one dimension, and not in another, unevenly.", "author": "Anaïs Nin"},
    {"quote": "The key to growth is the introduction of higher dimensions of consciousness into our awareness.", "author": "Lao Tzu"},
    {"quote": "Music in the soul can be heard by the universe.", "author": "Lao Tzu"},
    {"quote": "If you are depressed you are living in the past. If you are anxious you are living in the future. If you are at peace you are living in the present.", "author": "Lao Tzu"},
    {"quote": "New beginnings are often disguised as painful endings.", "author": "Lao Tzu"},
    {"quote": "When you are content to be simply yourself and don't compare or compete, everyone will respect you.", "author": "Lao Tzu"},
    {"quote": "Anticipate the difficult by managing the easy.", "author": "Lao Tzu"},
    {"quote": "Be content with what you have; rejoice in the way things are. When you realize there is nothing lacking, the whole world belongs to you.", "author": "Lao Tzu"},
    {"quote": "Respond intelligently even to unintelligent treatment.", "author": "Lao Tzu"},
    {"quote": "Do your work, then step back. The only path to serenity.", "author": "Lao Tzu"},
    {"quote": "The heart that gives, gathers.", "author": "Taoist Proverb"},
    {"quote": "The bamboo that bends is stronger than the oak that resists.", "author": "Japanese Proverb"},
    {"quote": "Fall seven times, stand up eight.", "author": "Japanese Proverb"},
    {"quote": "Vision without action is a daydream. Action without vision is a nightmare.", "author": "Japanese Proverb"},
    {"quote": "A silent man is the best to listen to.", "author": "Japanese Proverb"},
    {"quote": "The day you decide to do it is your lucky day.", "author": "Japanese Proverb"},
    {"quote": "Even monkeys fall from trees. Do not be discouraged by mistakes.", "author": "Japanese Proverb"},
    {"quote": "Better than a thousand hollow words, is one word that brings peace.", "author": "Buddha"},
    {"quote": "Radiate boundless love towards the entire world.", "author": "Buddha"},
    {"quote": "One moment can change a day, one day can change a life, and one life can change the world.", "author": "Buddha"},
    {"quote": "If you light a lamp for somebody, it will also brighten your path.", "author": "Buddha"},
    {"quote": "Work out your own salvation. Do not depend on others.", "author": "Buddha"},
    {"quote": "Your worst enemy cannot harm you as much as your own unguarded thoughts.", "author": "Buddha"},
    {"quote": "Drop by drop is the water pot filled. Likewise, the wise man, gathering it little by little, fills himself with good.", "author": "Buddha"},
    {"quote": "Do not learn how to react. Learn how to respond.", "author": "Buddha"},
    {"quote": "A disciplined mind brings happiness.", "author": "Buddha"},
    {"quote": "There is nothing so disobedient as an undisciplined mind, and there is nothing so obedient as a disciplined mind.", "author": "Buddha"},
    {"quote": "To understand the world, one must not look at it from a single point of view.", "author": "René Descartes"},
    {"quote": "I think, therefore I am.", "author": "René Descartes"},
    {"quote": "Conquer yourself rather than the world.", "author": "René Descartes"},
    {"quote": "It is not enough to have a good mind; the main thing is to use it well.", "author": "René Descartes"},
    {"quote": "Doubt is the origin of wisdom.", "author": "René Descartes"},
    {"quote": "Divide each difficulty into as many parts as is feasible and necessary to resolve it.", "author": "René Descartes"},
    {"quote": "The reading of all good books is like conversation with the finest men of past centuries.", "author": "René Descartes"},
    {"quote": "Except our own thoughts, there is nothing absolutely in our power.", "author": "René Descartes"},
    {"quote": "If you would be a real seeker after truth, it is necessary that at least once in your life you doubt, as far as possible, all things.", "author": "René Descartes"},
    {"quote": "The greatest minds are capable of the greatest vices as well as of the greatest virtues.", "author": "René Descartes"},
    {"quote": "Each problem that I solved became a rule which served afterwards to solve other problems.", "author": "René Descartes"},
    {"quote": "To know what people really think, observe what they do, rather than what they say.", "author": "René Descartes"},
    {"quote": "Perfection is not attainable, but if we chase perfection we can catch excellence.", "author": "Vince Lombardi"},
    {"quote": "It's not whether you get knocked down, it's whether you get up.", "author": "Vince Lombardi"},
    {"quote": "Confidence is contagious. So is lack of confidence.", "author": "Vince Lombardi"},
    {"quote": "The measure of who we are is what we do with what we have.", "author": "Vince Lombardi"},
    {"quote": "Individual commitment to a group effort—that is what makes a team work, a company work, a society work, a civilization work.", "author": "Vince Lombardi"},
    {"quote": "Mental toughness is essential to success.", "author": "Vince Lombardi"},
    {"quote": "Practice does not make perfect. Only perfect practice makes perfect.", "author": "Vince Lombardi"},
    {"quote": "Winning means you're willing to go longer, work harder, and give more than anyone else.", "author": "Vince Lombardi"},
    {"quote": "Self-respect is the fruit of discipline; the sense of dignity grows with the ability to say no to oneself.", "author": "Abraham Joshua Heschel"},
    {"quote": "Wonder is the root of all knowledge.", "author": "Abraham Joshua Heschel"},
    {"quote": "When I was young, I admired clever people. Now that I am old, I admire kind people.", "author": "Abraham Joshua Heschel"},
    {"quote": "Just to be is a blessing. Just to live is holy.", "author": "Abraham Joshua Heschel"},
    {"quote": "Self-knowledge is the beginning of self-improvement.", "author": "Baltasar Gracián"},
    {"quote": "A wise man gets more use from his enemies than a fool from his friends.", "author": "Baltasar Gracián"},
    {"quote": "Quit while you are ahead. All the best gamblers do.", "author": "Baltasar Gracián"},
    {"quote": "Know how to listen, and you will profit even from those who talk badly.", "author": "Plutarch"},
    {"quote": "To find fault is easy; to do better may be difficult.", "author": "Plutarch"},
    {"quote": "The mind is not a vessel to be filled, but a fire to be kindled.", "author": "Plutarch"},
    {"quote": "Rest is the sweet sauce of labor.", "author": "Plutarch"},
    {"quote": "Character is simply long-standing habit.", "author": "Plutarch"},
    {"quote": "Silence at the proper season is wisdom, and better than any words.", "author": "Plutarch"},
    {"quote": "An imbalance between rich and poor is the oldest and most fatal ailment of all republics.", "author": "Plutarch"},
    {"quote": "Painting is silent poetry, and poetry is painting that speaks.", "author": "Plutarch"},
    {"quote": "Small habits don't add up, they compound.", "author": "James Clear"},
    {"quote": "You do not rise to the level of your goals. You fall to the level of your systems.", "author": "James Clear"},
    {"quote": "Every action you take is a vote for the type of person you wish to become.", "author": "James Clear"},
    {"quote": "Fix the inputs and the outputs will fix themselves.", "author": "James Clear"},
    {"quote": "Be the designer of your world and not merely the consumer of it.", "author": "James Clear"},
    {"quote": "Habits are the compound interest of self-improvement.", "author": "James Clear"},
    {"quote": "True behavior change is identity change.", "author": "James Clear"},
    {"quote": "The most effective way to change your habits is to focus not on what you want to achieve, but on who you wish to become.", "author": "James Clear"},
    {"quote": "Patience is a key element of success.", "author": "Bill Gates"},
    {"quote": "It's fine to celebrate success but it is more important to heed the lessons of failure.", "author": "Bill Gates"},
    {"quote": "We all need people who will give us feedback. That's how we improve.", "author": "Bill Gates"},
    {"quote": "Don't compare yourself with anyone in this world... if you do so, you are insulting yourself.", "author": "Bill Gates"},
    {"quote": "Success is a lousy teacher. It seduces smart people into thinking they can't lose.", "author": "Bill Gates"},
    {"quote": "As we look ahead into the next century, leaders will be those who empower others.", "author": "Bill Gates"},
    {"quote": "Treatment of grief requires space, presence, and non-judgmental acceptance.", "author": "Elisabeth Kübler-Ross"},
    {"quote": "The most beautiful people we have known are those who have known defeat, known suffering, known struggle, known loss, and have found their way out of the depths.", "author": "Elisabeth Kübler-Ross"},
    {"quote": "People are like stained-glass windows. They sparkle and shine when the sun is out, but when the darkness sets in, their true beauty is revealed only if there is a light from within.", "author": "Elisabeth Kübler-Ross"},
    {"quote": "It's only when we truly know and understand that we have a limited time on earth that we will begin to live each day to the fullest.", "author": "Elisabeth Kübler-Ross"},
    {"quote": "Guilt is perhaps the most painful companion of death.", "author": "Elisabeth Kübler-Ross"},
    {"quote": "Learn to get in touch with the silence within yourself, and know that everything in life has purpose.", "author": "Elisabeth Kübler-Ross"},
    {"quote": "There is no need to go to India or anywhere else to find peace. You will find that deep place of silence right in your room, your garden or even your bathtub.", "author": "Elisabeth Kübler-Ross"},
    {"quote": "There are only two emotions: love and fear. All positive emotions come from love, all negative emotions from fear.", "author": "Elisabeth Kübler-Ross"},
    {"quote": "Live so that you wouldn't be ashamed to sell the family parrot to the town gossip.", "author": "Will Rogers"},
    {"quote": "Even if you're on the right track, you'll get run over if you just sit there.", "author": "Will Rogers"},
    {"quote": "Don't let yesterday take up too much of today.", "author": "Will Rogers"},
    {"quote": "Good judgment comes from experience, and a lot of that comes from bad judgment.", "author": "Will Rogers"},
    {"quote": "Everything is funny, as long as it's happening to somebody else.", "author": "Will Rogers"},
    {"quote": "If you find yourself in a hole, stop digging.", "author": "Will Rogers"},
    {"quote": "Wisdom is the reward you get for a lifetime of listening when you'd have preferred to talk.", "author": "Doug Larson"},
    {"quote": "To cultivate peace, seek first to quiet the inner storm before calming outer waters.", "author": "Modern Mind"}
]


def get_daily_quote():
    """
    Returns a deterministic daily quote based on day of year (1-365).
    Ensures a fresh, meaningful psychological quote every single day of the year.
    """
    day_of_year = datetime.now().timetuple().tm_yday
    idx = (day_of_year - 1) % len(PSYCHOLOGICAL_QUOTES)
    return PSYCHOLOGICAL_QUOTES[idx]


def get_random_quote():
    """Returns a completely random psychological quote from the 365 collection."""
    return random.choice(PSYCHOLOGICAL_QUOTES)
